# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_h3o_wrappers", use_symbols = TRUE, package_name = "h3o")

#' @docType package
#' @usage NULL
#' @useDynLib h3o, .registration = TRUE
NULL

h3_string_to_u64 <- function(x) .Call(wrap__h3_string_to_u64, x)

h3_int_to_string <- function(x) .Call(wrap__h3_int_to_string, x)

h3_base_cell <- function(x) .Call(wrap__h3_base_cell, x)

h3_from_string <- function(x) .Call(wrap__h3_from_string, x)

h3_from_points <- function(x, resolution) .Call(wrap__h3_from_points, x, resolution)

h3_boundaries_ <- function(x) .Call(wrap__h3_boundaries_, x)

h3_to_strings <- function(x) .Call(wrap__h3_to_strings, x)

sfg_to_cells <- function(x, resolution) .Call(wrap__sfg_to_cells, x, resolution)

sfc_to_cells <- function(x, resolution) .Call(wrap__sfc_to_cells, x, resolution)

